import * as Constants from "../constants/phone.enum";
import { IPhone } from "./IPhone.interface";

export const PhoneList: IPhone[] = [
    {
      name: 'Plum Ram 10',
      supportAndUpdates: Constants.Support.NotRel,
      usNetwork: [Constants.USNetwork.TM],
      voLTE: Constants.VoLTE.Yes,
      networkSignal: '',
      mms: Constants.MMS.Yes,
      hotspotTethering: Constants.Hotspot.No,
      usbType: Constants.USBType.Micro,
      unlocked: Constants.Unlocked.Yes,
      joseRating: 2,
      category: Constants.Category.Dumb,
      internationalNetwork: [''],
      operatingSystem: [''],
      gpsNavigation: [Constants.Navigation.No],
      physicalFormat: Constants.PhysicalFormat.Flip,
      removableBattery: Constants.RemovableBattery.Yes,
      browser: Constants.Browser.Yes,
      whatsApp: [Constants.WhatsApp.No],
      spotify: Constants.Spotify.No,
      signal: '',
      headphoneJack: '',
      camera: '',
      dualSim: '',
      podcastMusic: [''],
      wifiCalling: [''],
      externalStorage: '',
      twoFactorAuth: '',
      voiceToText: '',
      keyboard: [''],
      calendar: [''],
      screenType: [''],
      simType: [''],
      rugged: '',
      purchaseLink: '',
    },
    {
        name: 'Schok Classic',
        supportAndUpdates: Constants.Support.Yes,
        usNetwork: [Constants.USNetwork.TM, Constants.USNetwork.VZ, Constants.USNetwork.ATT],
        voLTE: Constants.VoLTE.Yes,
        networkSignal: '',
        mms: Constants.MMS.Yes,
        hotspotTethering: Constants.Hotspot.Yes,
        usbType: Constants.USBType.Micro,
        unlocked: Constants.Unlocked.Yes,
        joseRating: 4,
        category: Constants.Category.SmartFeat,
        internationalNetwork: [Constants.InternationalCarriers.Telstra, Constants.InternationalCarriers.VodafoneAU],
        operatingSystem: [''],
        gpsNavigation: [Constants.Navigation.Google, Constants.Navigation.Open, Constants.Navigation.Open],
        physicalFormat: Constants.PhysicalFormat.Flip,
        removableBattery: Constants.RemovableBattery.Yes,
        browser: Constants.Browser.Yes,
        whatsApp: [Constants.WhatsApp.YesNoWeb, Constants.WhatsApp.YesWeb],
        spotify: Constants.Spotify.Yes,
        signal: '',
        headphoneJack: '',
        camera: '',
        dualSim: '',
        podcastMusic: [''],
        wifiCalling: [''],
        externalStorage: '',
        twoFactorAuth: '',
        voiceToText: '',
        keyboard: [''],
        calendar: [''],
        screenType: [''],
        simType: [''],
        rugged: '',
        purchaseLink: '',
      },
  ];